"""initial schema

Revision ID: 7ef585856025
Revises: 
Create Date: 2026-01-14 19:04:54.055252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef585856025'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ORG_ADMIN', 'TEAM_MANAGER', 'SQUAD_LEADER', 'PLAYER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_created_at'), 'app_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('organization_admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_admin_id'), 'organization_admin', ['id'], unique=False)
    op.create_index(op.f('ix_organization_admin_organization_id'), 'organization_admin', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_admin_user_id'), 'organization_admin', ['user_id'], unique=False)
    op.create_table('player_vault',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vault_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_vault_id'), 'player_vault', ['id'], unique=False)
    op.create_index(op.f('ix_player_vault_user_id'), 'player_vault', ['user_id'], unique=True)
    op.create_table('team',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_created_at'), 'team', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_index(op.f('ix_team_organization_id'), 'team', ['organization_id'], unique=False)
    op.create_table('squad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_created_at'), 'squad', ['created_at'], unique=False)
    op.create_index(op.f('ix_squad_id'), 'squad', ['id'], unique=False)
    op.create_index(op.f('ix_squad_name'), 'squad', ['name'], unique=False)
    op.create_index(op.f('ix_squad_team_id'), 'squad', ['team_id'], unique=False)
    op.create_table('team_manager',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_manager_id'), 'team_manager', ['id'], unique=False)
    op.create_index(op.f('ix_team_manager_team_id'), 'team_manager', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_manager_user_id'), 'team_manager', ['user_id'], unique=False)
    op.create_table('squad_daily_goal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_daily_goal_completed_by_id'), 'squad_daily_goal', ['completed_by_id'], unique=False)
    op.create_index(op.f('ix_squad_daily_goal_created_at'), 'squad_daily_goal', ['created_at'], unique=False)
    op.create_index(op.f('ix_squad_daily_goal_created_by_id'), 'squad_daily_goal', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_squad_daily_goal_id'), 'squad_daily_goal', ['id'], unique=False)
    op.create_index(op.f('ix_squad_daily_goal_is_completed'), 'squad_daily_goal', ['is_completed'], unique=False)
    op.create_index(op.f('ix_squad_daily_goal_squad_id'), 'squad_daily_goal', ['squad_id'], unique=True)
    op.create_index(op.f('ix_squad_daily_goal_target_date'), 'squad_daily_goal', ['target_date'], unique=False)
    op.create_table('squad_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_event_created_at'), 'squad_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_squad_event_created_by_id'), 'squad_event', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_squad_event_end_time'), 'squad_event', ['end_time'], unique=False)
    op.create_index(op.f('ix_squad_event_event_type'), 'squad_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_squad_event_id'), 'squad_event', ['id'], unique=False)
    op.create_index(op.f('ix_squad_event_is_active'), 'squad_event', ['is_active'], unique=False)
    op.create_index(op.f('ix_squad_event_squad_id'), 'squad_event', ['squad_id'], unique=False)
    op.create_index(op.f('ix_squad_event_start_time'), 'squad_event', ['start_time'], unique=False)
    op.create_index(op.f('ix_squad_event_title'), 'squad_event', ['title'], unique=False)
    op.create_table('squad_leader',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_leader_id'), 'squad_leader', ['id'], unique=False)
    op.create_index(op.f('ix_squad_leader_squad_id'), 'squad_leader', ['squad_id'], unique=False)
    op.create_index(op.f('ix_squad_leader_user_id'), 'squad_leader', ['user_id'], unique=False)
    op.create_table('squad_membership',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('squad_id', 'user_id')
    )
    op.create_table('summon',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='summonstatus', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summon_created_at'), 'summon', ['created_at'], unique=False)
    op.create_index(op.f('ix_summon_created_by_id'), 'summon', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_summon_expires_at'), 'summon', ['expires_at'], unique=False)
    op.create_index(op.f('ix_summon_id'), 'summon', ['id'], unique=False)
    op.create_index(op.f('ix_summon_squad_id'), 'summon', ['squad_id'], unique=False)
    op.create_index(op.f('ix_summon_status'), 'summon', ['status'], unique=False)
    op.create_table('summon_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response_type', sa.Enum('PENDING', 'ACCEPT', 'DECLINE', 'MAYBE', name='responsetype', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['summon_id'], ['summon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summon_response_created_at'), 'summon_response', ['created_at'], unique=False)
    op.create_index(op.f('ix_summon_response_id'), 'summon_response', ['id'], unique=False)
    op.create_index(op.f('ix_summon_response_response_type'), 'summon_response', ['response_type'], unique=False)
    op.create_index(op.f('ix_summon_response_summon_id'), 'summon_response', ['summon_id'], unique=False)
    op.create_index(op.f('ix_summon_response_user_id'), 'summon_response', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summon_response_user_id'), table_name='summon_response')
    op.drop_index(op.f('ix_summon_response_summon_id'), table_name='summon_response')
    op.drop_index(op.f('ix_summon_response_response_type'), table_name='summon_response')
    op.drop_index(op.f('ix_summon_response_id'), table_name='summon_response')
    op.drop_index(op.f('ix_summon_response_created_at'), table_name='summon_response')
    op.drop_table('summon_response')
    op.drop_index(op.f('ix_summon_status'), table_name='summon')
    op.drop_index(op.f('ix_summon_squad_id'), table_name='summon')
    op.drop_index(op.f('ix_summon_id'), table_name='summon')
    op.drop_index(op.f('ix_summon_expires_at'), table_name='summon')
    op.drop_index(op.f('ix_summon_created_by_id'), table_name='summon')
    op.drop_index(op.f('ix_summon_created_at'), table_name='summon')
    op.drop_table('summon')
    op.drop_table('squad_membership')
    op.drop_index(op.f('ix_squad_leader_user_id'), table_name='squad_leader')
    op.drop_index(op.f('ix_squad_leader_squad_id'), table_name='squad_leader')
    op.drop_index(op.f('ix_squad_leader_id'), table_name='squad_leader')
    op.drop_table('squad_leader')
    op.drop_index(op.f('ix_squad_event_title'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_start_time'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_squad_id'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_is_active'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_id'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_event_type'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_end_time'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_created_by_id'), table_name='squad_event')
    op.drop_index(op.f('ix_squad_event_created_at'), table_name='squad_event')
    op.drop_table('squad_event')
    op.drop_index(op.f('ix_squad_daily_goal_target_date'), table_name='squad_daily_goal')
    op.drop_index(op.f('ix_squad_daily_goal_squad_id'), table_name='squad_daily_goal')
    op.drop_index(op.f('ix_squad_daily_goal_is_completed'), table_name='squad_daily_goal')
    op.drop_index(op.f('ix_squad_daily_goal_id'), table_name='squad_daily_goal')
    op.drop_index(op.f('ix_squad_daily_goal_created_by_id'), table_name='squad_daily_goal')
    op.drop_index(op.f('ix_squad_daily_goal_created_at'), table_name='squad_daily_goal')
    op.drop_index(op.f('ix_squad_daily_goal_completed_by_id'), table_name='squad_daily_goal')
    op.drop_table('squad_daily_goal')
    op.drop_index(op.f('ix_team_manager_user_id'), table_name='team_manager')
    op.drop_index(op.f('ix_team_manager_team_id'), table_name='team_manager')
    op.drop_index(op.f('ix_team_manager_id'), table_name='team_manager')
    op.drop_table('team_manager')
    op.drop_index(op.f('ix_squad_team_id'), table_name='squad')
    op.drop_index(op.f('ix_squad_name'), table_name='squad')
    op.drop_index(op.f('ix_squad_id'), table_name='squad')
    op.drop_index(op.f('ix_squad_created_at'), table_name='squad')
    op.drop_table('squad')
    op.drop_index(op.f('ix_team_organization_id'), table_name='team')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_index(op.f('ix_team_created_at'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_player_vault_user_id'), table_name='player_vault')
    op.drop_index(op.f('ix_player_vault_id'), table_name='player_vault')
    op.drop_table('player_vault')
    op.drop_index(op.f('ix_organization_admin_user_id'), table_name='organization_admin')
    op.drop_index(op.f('ix_organization_admin_organization_id'), table_name='organization_admin')
    op.drop_index(op.f('ix_organization_admin_id'), table_name='organization_admin')
    op.drop_table('organization_admin')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_created_at'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
